title: Nikos Argyropoulos - Portfolio
description: This is a portfolio that includes some of my most interesting projects.
show_downloads: false
google_analytics: false
email: n.argiropgeo@gmail.com
url: "https://www.nargyrop.com"
github_username: nargyrop
theme: jekyll-theme-slate